### ISSUE TITLE
Clarify timelines for deprecation trial

### ISSUE THREAD

**Issue by vardhman-singh-glean** [miketaylr/partitioned-storage-deprecation-trial-feedback#1]
https://developer.chrome.com/blog/storage-partitioning-deprecation-trial/ states that beginning gradually from Chrome version 115, third-party contexts will have partitioned storage, service workers, and communication APIs. 

Chrome 115 is expected to be released in early stable release in end of June going by [Chromium release schedule](https://chromiumdash.appspot.com/schedule).
 
However, storage partitioning is not mentioned in the roadmap (https://chromestatus.com/roadmap) for Chrome 115 / 116. 
Can someone verify the timeline?

**Comment by miketaylr** [comment]
Hi there, we're adding support for a 3P deprecation trial before we have 100% clarity on the timeline, but are optimistic about 115. I've just updated the target milestone on chromestatus, so it should be visible now. Thanks!
