### ISSUE TITLE
 Partitioned Storage Deprecation Trial works unexpectedly

### ISSUE THREAD

**Issue by rasulf** [miketaylr/partitioned-storage-deprecation-trial-feedback#11]
I have top level site _a.com_ that embeds _b.com_ iframe. I am using Broadcast Channel API to allow communication between the two - specifically - _b.com_ must be able to write into the (now partitioned) localStorage of a.com.

I participated in the Partitioned Storage Deprecation Trial and generated a deprecation token with origin as _b.com_ and included it in a meta tag in the head of my _a.com_ document, before the _b.com_ iframe loads. And everything works as expected - a.com localStorage is "unpartitioned" now.

I wanted to do the same thing for another c.com iframe that _a.com_ embeds. While testing I saw that if I created a Deprecation Trial Token with _a.com_ as origin - it allows c.com to access _a.com_'s localStorage. This is unexpected. I never really allowed _c.com_ to specifically allow access to _a.com_'s storage. Why is my storage unpartitioned over here?

**Comment by miketaylr** [comment]
Mind taking a look @arichiv?

**Comment by arichiv** [comment]
Are you sure the DT token you have in a meta tag on a.com wasn't a first-party token for a.com? You shouldn't be able to use a meta tag token at all unless it's a first-party token. If it is a first-party token for a.com then the behavior is expected as it would unpartition all iframes. Third-party tokens which impact just specific iframe domains have to be injected via script.

A few questions:
(1) what's the token? They aren't secret and can be posted here without issue.
(2) are the domains sub-domains of each other? It's expected that b.a.com embedded in a.com would be unpartitioned.
(3) are you trying to have a.com and b.com frames talk via a broadcast channel or local storage? That shouldn't ever be possible AFAIK. The wording in the question makes me a little confused.

**Comment by miketaylr** [comment]
Going to close given the lack of a response, but please comment if there are any remaining issues and we can re-open.
