### ISSUE TITLE
Storage Partitioning Despite Active DisableThirdPartyStoragePartitioning  Reverse Origin Trial

### ISSUE THREAD

**Issue by yoshiko-pg** [miketaylr/partitioned-storage-deprecation-trial-feedback#12]
@miketaylr @arichiv Hi. I am reporting a problem.

I am experiencing an issue with the DisableThirdPartyStoragePartitioning Reverse Origin Trial. 
Despite this Origin Trial being active on a site, its intended effect does not always apply. 

This Origin Trial is activated for a.com, which I have confirmed through the DevTools under Application > Frames > OriginTrials section. 
The site a.com embeds b.com within an iframe. 
b.com possesses specific values saved during top-level access.
These values should consistently be accessible from b.com when it is embedded in an iframe on a.com, but this is not always the case.

The expectation is that iframes embedded from the same origin should not be subjected to Storage Partitioning when this Origin Trial is active. 
However, after opening a.com in one tab where the Origin Trial disables Storage Partitioning and confirming through DevTools that the localStorage values from b.com at the top level are accessible, opening a.com in a different tab of the same window sometimes results in Storage Partitioning being enabled. In this new tab, DevTools does not show the localStorage values from b.com that were saved at the top level.
In both cases, the Origin Trial display in DevTools is still Enabled and the origin-tiral header is still sent.

I have also tested this in incognito mode with the same outcome. Furthermore, the issue persists in the Edge browser as well.

My team noticed this issue on February 19. I am not sure how long it has been occurring, but I believe that this problem did not occur until at least mid-December.

**Comment by arichiv** [comment]
You're saying the origin trial token is registered (via meta tag or HTTP Header) in the top-level window in both cases before the iframe is loaded? Is the origin trial token for a.com or is it a third-party token for b.com?

**Comment by yoshiko-pg** [comment]
@arichiv 

> You're saying the origin trial token is registered (via meta tag or HTTP Header) in the top-level window in both cases before the iframe is loaded?

Yes. The token for `DisableThirdPartyStoragePartitioning` is registered in the meta tag in the head of the top-level window, and can be seen in the view-source, so it was not inserted by executing JavaScript.
(In my first report, I wrote "request header", but that was a mistake, it was a token for another Origin Tiral.)

The token settings are: `Third party: false`, `Match Sub-Domains: true`.

> Is the origin trial token for a.com or is it a third-party token for b.com?

Token is for a.com. 
b.com has not taken any action for the origin trial.

**Comment by arichiv** [comment]
Do you have a demo that reproduces this error we could try? We already have internal testing of almost this exact pattern and aren't seeing the issue.

**Comment by yoshiko-pg** [comment]
@arichiv 
It is difficult to prepare an environment because we need an Origin Trial token to reproduce it, but it would be possible to take a video of what is happening at hand and share it.
May I have your email address to share the video with a closed audience?

**Comment by arichiv** [comment]
Here's a demo that can be copied/extended which uses an origin trial token: https://saa-beyond-cookies.glitch.me/ but tests a different API.

You can send a video to arichiv@chromium.org but chances are it won't have enough context for me to really debug.

My best guess is still that there's a race condition between inserting the token via JS into the header and starting to load the iframe. You said the token was visible in the web-inspector view-source, but that does reflect JS changes to the DOM. Are you sure it's actually in the HTML sent over the wire from the server?

**Comment by yoshiko-pg** [comment]
@arichiv 
Thank you for your email address. I will try to capture as much information as possible.

> there's a race condition between inserting the token via JS into the header and starting to load the iframe.

I thought about that possibility too, but what I told you is that the meta tag is present at the stage where the HTML is displayed in the `view-source:https://a.com` . I am not looking at it in the DevTools Element Inspector.
It's hard to imagine a timing issue in this case, right?

**Comment by arichiv** [comment]
Ah yes, in that case I agree it's unlikely to be a timing issue.

**Comment by yoshiko-pg** [comment]
@arichiv I shared the video with you via email. We hope you will check it out.

**Comment by arichiv** [comment]
Thanks for sending the video, can you verify whether or not it's an issue specific to DevTools storage view? If you use the console (setting the context at the top to the iframe's) is the data available programmatically? 

![Screenshot 2024-02-19 13 07 12](https://github.com/miketaylr/partitioned-storage-deprecation-trial-feedback/assets/666538/bb674d2b-de89-49c3-8357-69fc36ebb14d)

I'm wondering if DevTools isn't picking up the right bucket to render in its UI for debugging, but the correct one is actually connected to the iframe's JavaScript execution context.

**Comment by arichiv** [comment]
I could not repro this in DevTools storage view or in code via a demo I built here:
Outer frame (with OT token): https://partitioned-storage-deprecation-trial-feedback-issues-12.glitch.me/
Inner frame (get/set localStorage): https://partitioned-storage-deprecation-trial-feedback-issues-12-iframe.glitch.me/

Code here:
https://glitch.com/~partitioned-storage-deprecation-trial-feedback-issues-12
https://glitch.com/~partitioned-storage-deprecation-trial-feedback-issues-12-iframe

I'm using Version 122.0.6261.35 (Official Build) beta (64-bit)

**Comment by yoshiko-pg** [comment]
@arichiv 
Thanks for the confirmation.
I omitted it in the video, but it is the same when accessed from the program, it is not a DevTools display issue.

We are using Chrome 121.
The 122 update does not seem to have arrived yet.

We have checked internally and this did not seem to be happening until Feb 16th. (I have no guarantee that the patch version was up to date at that time.)
We don't know about the 17th and 18th as they were weekends and vacations.
The problem was confirmed on the 19th.

**Comment by arichiv** [comment]
Does the demo I posted work in your version of chrome? You should open https://partitioned-storage-deprecation-trial-feedback-issues-12.glitch.me/ and https://partitioned-storage-deprecation-trial-feedback-issues-12-iframe.glitch.me/ in different tabs, both should be setting/getting top-level storage.

**Comment by yoshiko-pg** [comment]
@arichiv The demo is working fine.
I was able to verify that the values can be shared every time, even after multiple reloads.

**Comment by arichiv** [comment]
To me that suggests it isn't about the specific version of chrome we are using (as it seems to be different by one milestone), but instead something about the underlying page that you're loading. To be sure, could you see if your bug reproduces on older (M120) and newer (M122) versions. The beta release channel for chrome is currently on M122, but as for M120 I'm not sure there's an official way to get it as it's no longer supported. I only suggest testing M120 as you say this worked on older versions of chrome.

Whether or not this bug is in Chrome, it will be hard to debug by me past this point as you found the demo I built doing (theoretically) the same thing to work consistently. Chrome is complex, so I cannot rule out that my simple demo works because it isn't invoking (in parallel) other supported behavior your site does, but without building a custom version of chrome to debug the issue directly on your site it's hard to reason about.

**Comment by yoshiko-pg** [comment]
Thanks for the suggestion.
I will try the Chrome versions of M120 and M122.

**Comment by yoshiko-pg** [comment]
Today, I tried the same M121 and the event no longer occurred.
As a difference, Tpcd was missing from the Origin Tiral of the site where the iframe was embedded.
Possible possibilities are interference between Tpcd and DisableThirdPartyStoragePartitioning, or interference with the token setting in the Response Header and meta tag.

The cause is unknown, but it is difficult for our team to pursue this cause, so we are going to fix it so that storage is not used between top level/iframe as a root cause.
We will close this issue. Thank you.
