### ISSUE TITLE
3rd party storage partion happens even with the origan trail token

### ISSUE THREAD

**Issue by amitwa1** [miketaylr/partitioned-storage-deprecation-trial-feedback#13]
I am trying to disable the 3rd party storage partition using the token
current state that doesn't work

1. create a token for storage 
![image](https://github.com/miketaylr/partitioned-storage-deprecation-trial-feedback/assets/153432188/12bc67e4-e328-4395-a952-243c0b2b2aa0)
2. activate flag 
![image](https://github.com/miketaylr/partitioned-storage-deprecation-trial-feedback/assets/153432188/4f47f073-3995-47da-92ea-11716f1b39dd)
3.add this token into a file called token.js(u will see 4 tokens there as I tried different options)
4. go to URL https://iframe-test.techsee.me/iframe2.html
5. click the add key value pair button
6. click on display to see that you see the value
7. go to URL https://lerna-test.pages.dev/storage-test/root/
8. click on either of the iframes display button. (I expected to see the value but currently I don't see anything )

**Comment by arichiv** [comment]
Under DevTools -> Application Tab -> Frames (select the one to inspect) -> Origin Trials you can see which tokens are active or inactive for which reasons. Be sure you're following the instructions here: https://developers.google.com/privacy-sandbox/3pcd/temporary-exceptions/storage-partitioning-deprecation-trial

There are two options, neither of which are happening right now:

(1) For a third-party token for https://iframe-test.techsee.me/ - https://lerna-test.pages.dev/storage-test/root/ must include a script from https://iframe-test.techsee.me/ that embeds the meta tag in the header *before* any iframes for https://iframe-test.techsee.me/ are loaded by https://lerna-test.pages.dev/storage-test/root/

(2) For a first-party token for https://lerna-test.pages.dev/ - The token must be in the HTTP headers or included via meta-tag in https://lerna-test.pages.dev/storage-test/root/ *before* any cross-site iframes are loaded.

**Comment by miketaylr** [comment]
Going to close as resolved, but please let us know if there are any remaining challenges.
