### ISSUE TITLE
Remove an Origin Trial

### ISSUE THREAD

**Issue by ShellyCR2024** [miketaylr/partitioned-storage-deprecation-trial-feedback#14]
I was hoping to find out how to remove the origin trial that appears in the Meta data in the first line of the head on every page. I did not join this origin trial nor did my developer so I'm not sure how it got there. But it shows up in the url inspection tool in my Google search console and I don't like having something in my coding that I have no idea what it does.   Can anyone help me?

**Comment by miketaylr** [comment]
Hi there - do you have a public URL to the website that you can share? It's not possible to enroll another site in an Origin Trial - it requires the ability to deploy an HTTP header (or a 1st-party script to inject the token). If you'd prefer to not post the URL here, you could send it via email to `miketaylr@google.com`.

**Comment by ShellyCR2024** [comment]
I would prefer to email you my site's url if you don't mind... Thank you. !

**Comment by ShellyCR2024** [comment]
I just sent you the url

**Comment by miketaylr** [comment]
Got it, thanks. Will follow up via email after some investigation.

**Comment by miketaylr** [comment]
Closing here and following up via email.

**Comment by miketaylr** [comment]
To close the loop here: the Deprecation Trial was being included by a 3rd party component.

**Comment by miketaylr** [comment]
To close the loop here: the Deprecation Trial was being included by a 3rd party component.

**Comment by miketaylr** [comment]
To close the loop here: the Deprecation Trial was being included by a 3rd party component.

**Comment by miketaylr** [comment]
whoa, 3 comments. sorry about that :/
