### ISSUE TITLE
Waiting for Chrome Origin Trials: DisableThirdPartyStoragePartitioning2 Registration Request Approval

### ISSUE THREAD

**Issue by CarlosAccedemeTrials** [miketaylr/partitioned-storage-deprecation-trial-feedback#16]
Hi Mike,

Hope this lines finds you well.

We have discovered the new DisableThirdPartyStoragePartitioning2 and requested a registration to use it as we did with the former DisableThirdPartyStoragePartitioning. We did the registration on Aug 5, 2024 12:07PM

Also we have commented in the Issue Tracker with the old DisableThirdPartyStoragePartitioning token, but no reply until now.

The trial DisableThirdPartyStoragePartitioning has been deprecated and the token we've got for it is not accepted and therefore our software is not running as expected.

Can you give us a clue of what to do to get the new token?

Thanks.

Kind regards,

Carlos

**Comment by miketaylr** [comment]
Hey there - thanks for the ping. We had some folks responsible for the review queue on PTO, but this should be taken care of today.
