### ISSUE TITLE
Request of New Trial for DisableThirdPartyStoragePartitioning2

### ISSUE THREAD

**Issue by jaissam10** [miketaylr/partitioned-storage-deprecation-trial-feedback#17]
Hi Team,

I’m currently working on an extension where we don’t utilize third-party cookies or storage partitioning, as the top-level site always begins with `chrome-extension:<id>//<dynamic_URL>`. However, we are now removing the prefix `chrome-extension://<id>` from the dynamic URL. This change results in a third-party context, and I have web-accessible resources on this page inside an iframe, which itself loads another iframe of my hosted CDN (https://abc.com).

Further details can be found here: https://github.com/privacysandbox/privacy-sandbox-dev-support/issues/409

Could you please assist me with a trial token? I wasn’t enrolled in the previous V1 token program.

Thank you!

CC: @miketaylr

**Comment by miketaylr** [comment]
> Could you please assist me with a trial token? I wasn’t enrolled in the previous V1 token program.

Unfortunately, renewals are only granted for sites that were previously enrolled (to intentionally limit the number of sites in the deprecation trial).

**Comment by jaissam10** [comment]
@miketaylr, I would appreciate it if there is an alternative way to obtain the trial token, as it is important for us.

**Comment by jaissam10** [comment]
@miketaylr, we are working on an extension within our organization. We request your approval to help us unlock it.

**Comment by miketaylr** [comment]
Please see https://developers.google.com/privacy-sandbox/blog/storage-partitioning-deprecation-trial-renewal#eligibility_criteria_and_review_process which describes the criteria. 

Can you explain why this need has only surfaced now, and not while the previous deprecation trial was available?

**Comment by jaissam10** [comment]
Hi @miketaylr ,

Thanks for your response.

I understand that this pertains to renewals, but we have a new requirement that emerged later. 

Currently, when opening a PDF, we load a Chrome extension page(chrome-extnsion://<id>/....) that contains our CDN iframe, meaning no storage partitioning is applied. 

However, we're now modifying our architecture. Going forward, when a PDF is opened, the URL will remain unchanged, and we'll embed an iframe for the Chrome extension page. This iframe will include a nested iframe from our CDN, displaying PDF data and additional features, provided the user has enabled the extension or granted access.

In this new setup, storage partitioning comes into play, and we're encountering some challenges with it.

Could you kindly provide a trial token while we continue to explore solutions for storage partitioning?

Thank you!

**Comment by miketaylr** [comment]
> Could you kindly provide a trial token while we continue to explore solutions for storage partitioning?

I've added some comment in the internal deprecation trial application issue - it's probably easier to continue conversation there, thanks.
