### ISSUE TITLE
Clarification on 3P deprecation trial

### ISSUE THREAD

**Issue by vardhman-singh-glean** [miketaylr/partitioned-storage-deprecation-trial-feedback#2]
Apologies for not including this query in the previous issue. I recently came across this discussion on adding support for a 3P deprecation trial on the [Intent-To-Ship](https://groups.google.com/a/chromium.org/g/blink-dev/c/24hK6DKJnqY/m/M112wAPCAwAJ) and the associated [task](https://bugs.chromium.org/p/chromium/issues/detail?id=1441411) for the same.

We have a similar use-case which will be affected by storage partitioning, where the embedded frame could have a URL of the form `https://<subdomain>.example.net` and would want to opt-in to the 3P deprecation trial for all subdomains.

Could you clarify if the 3P deprecation trial is confirmed and if so, whether it will allow for subdomain matching as well, i.e.,:
<img width="574" alt="Screenshot 2023-05-09 at 11 25 15 PM" src="https://github.com/miketaylr/partitioned-storage-deprecation-trial-feedback/assets/108234710/f1025199-6378-450b-a63e-416a3057e5c9">

**Comment by miketaylr** [comment]
Hi @vardhman-singh-glean, yep https://bugs.chromium.org/p/chromium/issues/detail?id=1441411 is the correct bug for tracking the 3P deprecation trial work. Subdomain matching should also work.

It would be great if you can continue watching the bug and do some testing once it lands in Canary (commenting on the bug if it doesn't!). Thanks.

cc @arichiv (who is doing the implementation work)

**Comment by miketaylr** [comment]
This is now implemented. See https://developer.chrome.com/blog/storage-partitioning-deprecation-trial/
