### ISSUE TITLE
Deprecation Trial Not Working

### ISSUE THREAD

**Issue by Octophi** [miketaylr/partitioned-storage-deprecation-trial-feedback#4]
Hi Team, I have had some troubles enabling this deprecation trial so I wanted to check if I was doing anything wrong.. I have successfully added my origin-trial meta tag, which looks like tag looks like <meta http-equiv="origin-trial" content="[token]"> to my top-level page. The token is the right token for my domain. When I go to the Application tab in Chrome DevTools, I still see the storage being partitioned by top-level site. Any ideas what might be going wrong?

<img width="1009" alt="Screenshot 2023-08-03 at 10 58 52 AM" src="https://github.com/miketaylr/partitioned-storage-deprecation-trial-feedback/assets/16705282/e28b37cd-923a-4015-995c-dce665107b68">

In addition, I also registered my token to work in a third party context and tried to add the JavaScript to add the meta tag to the page so that when it gets iframed it will request to opt in to the deprecation trial. In this case, I also successfully inserted the origin-trial meta tag but I still see the storage getting partitioned.

**Comment by miketaylr** [comment]
Thanks for the feedback. Let me work on a reduced test case to verify.

**Comment by miketaylr** [comment]
@Octophi would you mind pasting your test OT token here? (It's just a base64 encoded object - nothing super secret about it). I'm curious if you selected the subdomain matching checkbox.

Also, here's a pretty simple example using sessionStorage, but the particular storage interface shouldn't matter:

https://rogue-lace-join.glitch.me/

See also https://miketaylr.com/misc/3pspdt.js and `view-source:https://miketaylr.com/misc/sptest.html` to understand the setup.

The basic premise is that you should inject the 3P OT token in the top-level frame's head before creating and injecting any 3P iframes.

**Comment by Octophi** [comment]
Sure, my token is AysPnqWJeE+bXqBmzsgbertfahuz7WDiHl03RGtRm/e5Kw309x5CWqk0/CQSpn1sRxV9SNxioru5KZNfu3jaFwgAAACOeyJvcmlnaW4iOiJodHRwczovL2ZvcmNlLmNvbTo0NDMiLCJmZWF0dXJlIjoiRGlzYWJsZVRoaXJkUGFydHlTdG9yYWdlUGFydGl0aW9uaW5nIiwiZXhwaXJ5IjoxNzI1NDA3OTk5LCJpc1N1YmRvbWFpbiI6dHJ1ZSwiaXNUaGlyZFBhcnR5Ijp0cnVlfQ==

I can see it inserted into a meta tag on the top-level page but it doesn't seem to be stopping the partitioning from occurring.

**Comment by Octophi** [comment]
Also just to check, does a token have to work either in a third-party context OR from being injected on the top-level domain, or can it cover both scenarios?

**Comment by Octophi** [comment]
Also, are there any additional complications if we have an iframe within an iframe within a page?

**Comment by miketaylr** [comment]
Let me tag in @arichiv on the question of iframes within iframes... can you describe the setup a little bit more?

**Comment by Octophi** [comment]
I have an endpoint which I control, which iframes in another endpoint which I control, which I then use to iframe in a third-party endpoint which I do not control. I want to disable storage partitioning and have been trying to do so by adding the meta tag to the HTML for the top-level site. However, it doesn't appear to be working at the moment.

**Comment by miketaylr** [comment]
OK, so you have `a.com` which frames `b.com` which frames `c.com` and you want unpartitioned storage for `c.com`, correct?

**Comment by Octophi** [comment]
Yup, exactly. I control a.com and b.com but not c.com

**Comment by arichiv** [comment]
Can you describe the specific origins that are embedding each other? What level is https://force.com:443?

**Comment by arichiv** [comment]
I ask because your token is for https://force.com:443 and is a Third-Party token. There are two options if we consider the example of a.com embedding b.com:

1. a.com can include a first-party token for a.com, this will unpartition all subframes on any origins
2. a.com can include a third-party token for b.com via some script on b.com, this will unpartition all subframes for b.com (and their descendants) only

**Comment by arichiv** [comment]
Also, it's important to note that in case (2), the token *must* be injected via a script from b.com. a.com cannot inject it itself or the token will be ignored.

**Comment by Octophi** [comment]
Ok, got it, so we cannot use the same token for both a third-party context and a first-party context. 

Currently, I have a page https://joey-dev-ed--c.develop.vf.localhost.sfdcdev.force.com:6101/apex/CanvasPage which iframes in a page on the salesforce.com registrable domain, which then iframes in a page in herokuapp.com. I am inserting a meta tag on the top-level page which looks like 

\<meta http-equiv="origin-trial" content="Apc8pO8JGSLKZOkQf8NfSRklYVLkT+dvbMIj6kiVHMH0XbsXr9l0lOAfVurJHlbSiVBqgeVxbjgl3tamPLlATw8AAAB6eyJvcmlnaW4iOiJodHRwczovL2ZvcmNlLmNvbTo0NDMiLCJmZWF0dXJlIjoiRGlzYWJsZVRoaXJkUGFydHlTdG9yYWdlUGFydGl0aW9uaW5nIiwiZXhwaXJ5IjoxNzI1NDA3OTk5LCJpc1N1YmRvbWFpbiI6dHJ1ZX0=">

I believe this is a first-party token associated with force.com. It still doesn't appear to be working, though. Am I missing something?
<img width="565" alt="Screenshot 2023-08-04 at 2 19 00 PM" src="https://github.com/miketaylr/partitioned-storage-deprecation-trial-feedback/assets/16705282/cfc743dc-b0f1-4ffe-bb6c-c34da98827b3">

**Comment by Octophi** [comment]
Also not directly related, but let's say I have something which might be served from either of two different domains. Is it possible to specify two origin trial tokens on the page and for either of them to be considered?

**Comment by miketaylr** [comment]
That should be possible, yes.

**Comment by Octophi** [comment]
Ok after some more debugging I figured out why it wasn't working - my dev environment was not running https on the default port 443, so the token wasn't associated with the correct origin. Thanks y'all for answering all my questions so promptly.

**Comment by miketaylr** [comment]
Glad to hear you got it sorted!
