### ISSUE TITLE
Help with 3P Deprecation Trial Token Use Case

### ISSUE THREAD

**Issue by Octophi** [miketaylr/partitioned-storage-deprecation-trial-feedback#5]
Hi again, I had another question regarding my particular use case of the 3P deprecation trial. 

I have a Chrome extension with some JS which creates an iframe and loads in a site I own. In loading in the site I own, it actually goes across two domains. It deals with one first while logging in, and then upon authenticating, it goes to a different domain. 

I added logic to add the tokens for both of the domains to the top-level document before creating the iframe. Unfortunately, it doesn't seem to be unpartitioning the storage. Why might this be happening? 

My theories were either 

1. Because it does additional navigation from one domain to another inside the iframe, which messes things up
2. because the JS is actually included as <script src="chrome-extension://<name of js file"/> which is different from the domain of the page I'm actually trying to access 

However, I'm not sure how significant either of these might be

**Comment by miketaylr** [comment]
Apologies for missing this issue - I just got back from some travel. 

Do I understand the setup correctly?

0. Some (3rd party?) origin trial tokens are injected in a top-level page (is this `a.com`, or the chrome extension background page?)
1. A Chrome extension with host permission for `a.com` (which you own?) creates and injects an iframe in `a.com`.
2. The iframe loads `b.com` for authentication, then navigates to `c.com`? 
3. You expect to read unpartitioned storage from somewhere (`b.com` and `c.com`?). Do you own either of these?

Can you clarify what storage APIs you're trying to read from, and when exactly? Thanks!

**Comment by miketaylr** [comment]
Going to close this given the lack of a response, but please comment if you're still running into any issues.
