### ISSUE TITLE
requestStorageAccess not yet working

### ISSUE THREAD

**Issue by hilnius** [miketaylr/partitioned-storage-deprecation-trial-feedback#7]
Hello
If i understand correctly : 
When site a.com includes an iframe on b.com, if I control both sites, and wish to share b.com's data (the iframe) with a.com (the parent window), I should call `requestStorageAccess` from my b.com page and then use postMessage to transfer data to a.com. Is that correct ?

If it is, then at the moment, it's pretty hard to test that "Experimental third-party storage partitioning." flag in Chrome. Indeed, in order to share data through an iframe (and some `postMessages` checking the correct origins), with that new flag on, there needs to be a way for the child iframe to actually access the storage of b.com (a correct workaround). and currently `requestStorageAccess` doesn't work as expected - so I can't really keep this flag enabled.

So just saying : I don't think that this feature can be rolled out without a correct workaround for this use case - using the `requestStorageAccess` would be the favorite candidate from what I can understand - but it's still not ready so it's hard to test this feature yet.

**Comment by miketaylr** [comment]
Apologies to miss this issue. We're prototyping a mode for requestStorageAccess to request a handle to unpartitioned storage. There should be an origin trial you can test soon: https://groups.google.com/a/chromium.org/g/blink-dev/c/SEL7N-xIE5s/m/8puhB8T1BgAJ
