### ISSUE TITLE
looking for guidence on registration of deprecation trial

### ISSUE THREAD

**Issue by lqw1111** [miketaylr/partitioned-storage-deprecation-trial-feedback#8]
Hi, 

I have a couple of question about registration of deprecation trial

**Use case:**
I have couple of website. For example, I have `a.web.com`, `b.web.com`, `c.web.com` etc.. All those website are under the same domain - `web.com`. 
And I have `iframe.com`. `iframe.com` will be embedded in those website as an iframe.
All those `xxx.web.com` website will `postMessage` data object to the `iframe.com`, and `iframe.com` will save the data object into the localStroage.
And user will visit `iframe.com` to see all data object which are collected from `a.web.com` `b.web.com` and `c.web.com` etc.

In this case, in order to register in the deprecation trial.
1. What is the correct "Web Origin", is it "https://web.com"? because the subdomain will change, but domain will always be `web.com`, so what should I put here?
2. Should I select those two options?
```
Third-party matching. The token will be injected by script on other origins.
I need a token to match all subdomains of the origin.
```
3. Which website should be the top-level site, like I should put the `<meta>` tag and token in which website's html. The `iframe.com` or `xxx.web.com`?
4. Once I enroll into the deprecation trial, If want to access the localStorage, should I just calling `window.localStroage.getItem(key)`, just like we do not parationing the storage before. Or is there any other steps needed, like calling the Storage Access API (e.g `requestStorageApi()`)?

Thank you so much for the guidence!

<img width="620" alt="image" src="https://github.com/miketaylr/partitioned-storage-deprecation-trial-feedback/assets/32659870/6c33cef2-03cd-41e4-82f2-a07ae32199be">

**Comment by arichiv** [comment]
Since you manage the top-level origin, you probably want to generate a token for web.com that matches all subdomains and isn't third-party. If you're in the trial and properly include the token, all iframes loaded on that page will have unpartitioned storage.

**Comment by miketaylr** [comment]
Going to close this as resolved, given the lack of any follow up responses.
