### ISSUE TITLE
Not getting expected behavior with StoragePartitioning Deprecation Trial token and SharedWorkers

### ISSUE THREAD

**Issue by bretticus-mc** [miketaylr/partitioned-storage-deprecation-trial-feedback#9]
I'm testing the Storage Partitioning Deprecation Trial but am still getting two SharedWorkers when I embed a site and have the site at the top-level at the same time. I'm loading https://embedded-site.com:8000, which creates a SharedWorker, first. Then I load https://customer.com:8000, which has https://embedded-site.com:8000 embedded in an iframe. I'm seeing the token is installed successfully in the DevTools. The token is being injected via <script>. Made sure the token is for the entire origin and not just https://embedded-site.com. I've attached a video of my test. I was expecting there to be only one SharedWorker for https://embedded-site.com:8000 in this scenario. 

Setup:
**Top Level Site** (customer.com:8000): https://pastebin.com/aHHLtRVU
**Embedded Site** (embedded-site.com:8000): https://pastebin.com/LdsN0fW6
**Script to inject tokens** (embedded-site.com:8000): https://pastebin.com/2BBV6QgD
**SharedWorker**(embedded-site.com:8000): https://pastebin.com/kp8GzzyP

Token 3P with no subdomain matching: 
```
AwduSBrLD9A9CkzCM0oFqkxWgoC3PFt+ZLhDSZk6m1iFVr+7Upwft7ctuRpmXLuuZCOEdNSHF2z2fyRruFCJGQoAAACEeyJvcmlnaW4iOiJodHRwczovL2VtYmVkZGVkLXNpdGUuY29tOjgwMDAiLCJmZWF0dXJlIjoiRGlzYWJsZVRoaXJkUGFydHlTdG9yYWdlUGFydGl0aW9uaW5nIiwiZXhwaXJ5IjoxNzI1NDA3OTk5LCJpc1RoaXJkUGFydHkiOnRydWV9
```

<img width="830" alt="image" src="https://github.com/miketaylr/partitioned-storage-deprecation-trial-feedback/assets/24796774/5a4d2710-eba1-4685-90c1-62ec8cd36bae">

https://github.com/miketaylr/partitioned-storage-deprecation-trial-feedback/assets/24796774/2ec0d508-b9a1-4331-87f8-e79bb35f326f

**Comment by miketaylr** [comment]
@arichiv would you mind taking a look? I suspect the issue is not injecting the token into the top-level frame (vs the embedded frame), but you're the expert.

**Comment by arichiv** [comment]
@miketaylr is right, the issue is that customer.com needs to include/execute embedded-site.com/deprecation_trial.js *before* the iframe for embedded-site.com is loaded. Once any given frame loads whether or not storage partitioning is enabled is fixed.

**Comment by bretticus-mc** [comment]
I see. It's working as expected now. Thanks for the clarification.
